### ISSUE TITLE
Argument documentation doesn't match arguments

### ISSUE THREAD

**Issue by daviddoria** [koraykv/unsup#32]
In these files:

https://github.com/koraykv/unsup/blob/master/SpatialConvFistaL1.lua
https://github.com/koraykv/unsup/blob/master/ConvPsd.lua

the documentation has 'inputFeatures' and 'outputFeatures', but these are not arguments to the function. The function also has the argument 'conntable', which is not described.

**Comment by koraykv** [comment]
contable is a connection table that is fed into nn.SpatialConvolutionMap (https://github.com/torch/DEPRECEATED-torch7-distro/blob/master/extra/nn/SpatialConvolutionMap.lua). There are examples and functions in 'nn' to create these tables.

**Comment by daviddoria** [comment]
The documentation in these files was not changed - shouldn't the issue stay open until it is?

**Comment by koraykv** [comment]
just did. thanks.
